// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Msg message returned by server side if there is any
	Msg    *string `json:"msg,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Business defines model for Business.
type Business struct {
	Config   *Config `json:"config,omitempty"`
	CreateAt *string `json:"create_at,omitempty"`
	Id       *string `json:"id,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
	UpdateAt *string `json:"update_at,omitempty"`
}

// Businesses defines model for Businesses.
type Businesses struct {
	Businesses *[]Business `json:"businesses,omitempty"`
}

// Config defines model for Config.
type Config struct {
	DataSourceConfig *[]DatabaseConnectConfig `json:"dataSourceConfig,omitempty"`
}

// DatabaseConnectConfig defines model for DatabaseConnectConfig.
type DatabaseConnectConfig struct {
	Database     *string `json:"database,omitempty"`
	DatabaseType *string `json:"databaseType,omitempty"`
	Host         *string `json:"host,omitempty"`
	Id           *string `json:"id,omitempty"`
	Password     *string `json:"password,omitempty"`
	Port         *int    `json:"port,omitempty"`
	Title        *string `json:"title,omitempty"`
	Username     *string `json:"username,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	UserName string `json:"userName"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	AccountId        *string `json:"accountId,omitempty"`
	Avatar           *string `json:"avatar,omitempty"`
	Email            *string `json:"email,omitempty"`
	Name             *string `json:"name,omitempty"`
	Permissions      *string `json:"permissions,omitempty"`
	RegistrationTime *string `json:"registrationTime,omitempty"`
}

// ResponseBusinessList defines model for ResponseBusinessList.
type ResponseBusinessList = Businesses

// ResponseDatabaseList defines model for ResponseDatabaseList.
type ResponseDatabaseList = Config

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseUserInfo defines model for ResponseUserInfo.
type ResponseUserInfo = UserInfo

// DeleteBusinessParams defines parameters for DeleteBusiness.
type DeleteBusinessParams struct {
	// Id Business ID
	Id string `form:"id" json:"id"`
}

// CreateBusinessJSONRequestBody defines body for CreateBusiness for application/json ContentType.
type CreateBusinessJSONRequestBody = Business

// UpdateBusinessJSONRequestBody defines body for UpdateBusiness for application/json ContentType.
type UpdateBusinessJSONRequestBody = Business

// CreatePostgresDatabaseJSONRequestBody defines body for CreatePostgresDatabase for application/json ContentType.
type CreatePostgresDatabaseJSONRequestBody = DatabaseConnectConfig

// UpdatePostgresDatabaseJSONRequestBody defines body for UpdatePostgresDatabase for application/json ContentType.
type UpdatePostgresDatabaseJSONRequestBody = DatabaseConnectConfig

// CreateRedisDatabaseJSONRequestBody defines body for CreateRedisDatabase for application/json ContentType.
type CreateRedisDatabaseJSONRequestBody = DatabaseConnectConfig

// UpdateRedisDatabaseJSONRequestBody defines body for UpdateRedisDatabase for application/json ContentType.
type UpdateRedisDatabaseJSONRequestBody = DatabaseConnectConfig

// TestDatabaseConnectionJSONRequestBody defines body for TestDatabaseConnection for application/json ContentType.
type TestDatabaseConnectionJSONRequestBody = DatabaseConnectConfig

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete Business
	// (DELETE /business)
	DeleteBusiness(ctx echo.Context, params DeleteBusinessParams) error
	// Create Business
	// (POST /business)
	CreateBusiness(ctx echo.Context) error
	// Update Business
	// (PUT /business)
	UpdateBusiness(ctx echo.Context) error
	// Get Business List
	// (GET /businesses)
	GetBusinesses(ctx echo.Context) error
	// Get Database Connection Configure List
	// (GET /database)
	GetDatabaseConfigureList(ctx echo.Context) error
	// Get Postgres Database List
	// (GET /database/postgres)
	GetPostgresDatabaseList(ctx echo.Context) error
	// Create Postgres Database
	// (POST /database/postgres)
	CreatePostgresDatabase(ctx echo.Context) error
	// Update Postgres Database
	// (PUT /database/postgres)
	UpdatePostgresDatabase(ctx echo.Context) error
	// Get Redis Database List
	// (GET /database/redis)
	GetRedisDatabaseList(ctx echo.Context) error
	// Create Redis Database
	// (POST /database/redis)
	CreateRedisDatabase(ctx echo.Context) error
	// Update Redis Database
	// (PUT /database/redis)
	UpdateRedisDatabase(ctx echo.Context) error
	// Test Database Connection
	// (POST /database/test)
	TestDatabaseConnection(ctx echo.Context) error
	// Login to Dashboard
	// (POST /user/login)
	Login(ctx echo.Context) error
	// UserInfo
	// (GET /user/userInfo)
	UserInfo(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteBusiness converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBusiness(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteBusinessParams
	// ------------- Required query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, true, "id", ctx.QueryParams(), &params.Id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteBusiness(ctx, params)
	return err
}

// CreateBusiness converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBusiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateBusiness(ctx)
	return err
}

// UpdateBusiness converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBusiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateBusiness(ctx)
	return err
}

// GetBusinesses converts echo context to params.
func (w *ServerInterfaceWrapper) GetBusinesses(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBusinesses(ctx)
	return err
}

// GetDatabaseConfigureList converts echo context to params.
func (w *ServerInterfaceWrapper) GetDatabaseConfigureList(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDatabaseConfigureList(ctx)
	return err
}

// GetPostgresDatabaseList converts echo context to params.
func (w *ServerInterfaceWrapper) GetPostgresDatabaseList(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPostgresDatabaseList(ctx)
	return err
}

// CreatePostgresDatabase converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePostgresDatabase(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreatePostgresDatabase(ctx)
	return err
}

// UpdatePostgresDatabase converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatePostgresDatabase(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatePostgresDatabase(ctx)
	return err
}

// GetRedisDatabaseList converts echo context to params.
func (w *ServerInterfaceWrapper) GetRedisDatabaseList(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRedisDatabaseList(ctx)
	return err
}

// CreateRedisDatabase converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRedisDatabase(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateRedisDatabase(ctx)
	return err
}

// UpdateRedisDatabase converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateRedisDatabase(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateRedisDatabase(ctx)
	return err
}

// TestDatabaseConnection converts echo context to params.
func (w *ServerInterfaceWrapper) TestDatabaseConnection(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TestDatabaseConnection(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Login(ctx)
	return err
}

// UserInfo converts echo context to params.
func (w *ServerInterfaceWrapper) UserInfo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UserInfo(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/business", wrapper.DeleteBusiness)
	router.POST(baseURL+"/business", wrapper.CreateBusiness)
	router.PUT(baseURL+"/business", wrapper.UpdateBusiness)
	router.GET(baseURL+"/businesses", wrapper.GetBusinesses)
	router.GET(baseURL+"/database", wrapper.GetDatabaseConfigureList)
	router.GET(baseURL+"/database/postgres", wrapper.GetPostgresDatabaseList)
	router.POST(baseURL+"/database/postgres", wrapper.CreatePostgresDatabase)
	router.PUT(baseURL+"/database/postgres", wrapper.UpdatePostgresDatabase)
	router.GET(baseURL+"/database/redis", wrapper.GetRedisDatabaseList)
	router.POST(baseURL+"/database/redis", wrapper.CreateRedisDatabase)
	router.PUT(baseURL+"/database/redis", wrapper.UpdateRedisDatabase)
	router.POST(baseURL+"/database/test", wrapper.TestDatabaseConnection)
	router.POST(baseURL+"/user/login", wrapper.Login)
	router.GET(baseURL+"/user/userInfo", wrapper.UserInfo)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RZTW/bRhP+K8S875Ex5Y+2KG/xRwMhrm3YTi5BEKzIEbWJuEvvLm0rhoD20KK3XooC",
	"vfXUqy8F+ovSuv+i2KUo7UpLl/4IIqiAAYvU7M7M8wyfGa6uIOF5wRkyJSG+AoGy4EyiuTieXGyXkjKU",
	"cp9Kpe8nnClk5iMpiiFNiKKcRW8lZ/qeTAaYE/3p/wL7EMP/opmTqPpWRvWmKGE8HoeQokwELfROEIPj",
	"chxOQ9klivSIxEcNZYezPs3uEkaXKRSMDE9QnKPYE4KLFtHgJcmLIeqPOUpJMoQY6q2Caq+g2mwctoWR",
	"SKyj8mXQuH296ICrr3jJ0vvGf8BVUG3waDE7W9aGh88fr/T+xf/hc9vxC4miy/r8bgCRJOElU90UYiBp",
	"ThmEQM6JIgJiGChVyDiKsos1MqQFGfHeW0yUXEt4Hr3nMhK5LLhQZBhtU/K+T9hlTvKDY355+fLyHVkr",
	"WAYhYE7oEGKAEBjJ0XJUoMiplJQzad0VmFGphAn5lJoFG52NzpPO+pPOetDpxOavPY1TYDwQWt/V2xlJ",
	"caCPr6AQvEChaCU4ucz0P3erSakFAlUpGKZBbxTIqpglTTGg/UANUGBAZUDYSANT0wA3v//24cc//vzh",
	"55tvvvtw/f1fv37790+/3FxfQwhqVGgLqQRlmUlaEVVKh0ZA87QsGOukamlYzCKp5KSl6ISQCCQK3xDl",
	"+vZx4wmbpu6ymu0FQ0VVVZptbM0N2/Sk+/XR/t6bl4ene74FZZHeOwcbTfTg2XO+owpz2ba5zHIBIgQZ",
	"Vc52pgS5jlKiyAkvRYIzi1bu6q60wxnDRM2oXfTtN/WGos1cOL0FUJueLnAmMKXSt2TA5RxRQ56Qobnd",
	"psR6SYrqDC/WNze2NrweCiLlBRdta1OLnWv6+eYXX84sKVOYoWgo42OdZ1Aj6y1PqZtg3q78NU37PKPs",
	"GM9KrJBy2bljdtr7QWvvWqhJesiGI4iVKFFfn5VUYArxq9leFsavxyHYXcoN1upEraKtu5Rt/DgNa8HV",
	"pIPZnnxmrZmb63ytVix2xXsImGaNTtB3u9fTo27Q5yLYp++oebiq8gVzHTw96kII5yhkZX2+rkPiBTJS",
	"UIhhc62ztmmoVgOTUNSz2k6KQ1QmYM23ycDMG7vm/lQD9XJBclQoJMSvrhpm3KC7CzoLiOGsRDGajRU0",
	"BbsIq6KczQjzaLwO3deIjU6nSUCndpE15o1D2OpstV8ynWDHIXx2F1++Kd7MK2WeEzGaIhnY7aSYaKcL",
	"+Y7p4RbkotKObZ6OHv2VyTdwVQE4ka4KCZ7UitLDwQszg3xCDqoAVpKDhdTG4UyLquwy9HDyDJU12j0E",
	"j/lX8WVB5hmqKSxBFZzGxh7gmpCxZsE+zUpRnWo8BCTneGTJQKpjCyajL+UsmGbuQS7SSpuJ24vraGLj",
	"JL6qZVYnO4OyjvK2pjQP0UcSxoZ3oMZOtZDMCrYsb4639K5lo2qi+itNVXOOjhhV79K3KJF5Cf1PyJD7",
	"ut1KgxxwlkSA5k4NVk99FhO8RXqWiqHJM7m6DDUk6CiOqo+evM/VKUo1h6fG7hMTp6PyDXqrxF1zjpq+",
	"UqKIhjyjrJk7c7j4kahyDi49DFW+V4gOk1CgeLBL5KDHiUgtIkrrVNTbuKfHpg8BZPZj1xIpjPXj3Pif",
	"AAAA//+RUb1D5h8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
